apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:3ry/aIIhOhfu16xIgN5K0DL93R33rRt59mPrenwaijwmLHAYjVIRPw==,iv:/2SS3LDZmyRpiZNVmF8U217M+z3xeXFm2mkpd6wKfCU=,tag:toxCI2ixZf1JSwNT6Achkw==,type:str]
sops:
  age:
    - recipient: age1dq2tahm820v40c0d55p0x84hlt9tlunh5lq32gr9lszkwelpv4mqv2wc0v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOXZyM29lU2FDOHB5c0o2
        RGpKUkE2QVhRZkxyL3dtcnBCdjRNaG45bXlrCkxvT0JqRjBxV0trZjR0UytoWFBV
        elAxcXY0Q0VJRnZuSEZRNDFnY3F2MmMKLS0tIGJqakt4Lzk4bzJlZDlLTlFkVk5m
        bGlEWHhsTUl5ZTNoYjQwbFord0luazAKUDaz1Liynr+AOFN7QU/1PHUTeU80UZOf
        siCzjmlUxHBU/qMTbdebcOeqedH51bkKGs4aw1LXV55Vt+rgq9tUCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T17:45:29Z"
  mac: ENC[AES256_GCM,data:1ICCwAsfU7wO5OqJdSwbkM3tmoeULgtwn8ItBXe64CxLNxam5X0+pEUHu/n9O/kB2Tf/eufWXdDUSFpq1y7HpfgNDdVOQG/dPyudVZ08B8N0s30npPPZoiuDwPPF0flYQG8z1/scZFU6McXjXxiAlTTlpXMSwcMj4ziJwIHEimQ=,iv:ekSTZYtzD/gSeK5L4Nhory42xHEB6cDzGb2KAool5Rw=,tag:evh/EfVTv8GwBBLegRGehA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
