apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Tq89h2m0DKsB2snAik1/4+mkIjWgCL1GxOTEJk9i4dFHEVWxhga8CA==,iv:Ep0SkM3Ugodxukm27LN5hPivw5uNEZ0DaurzgB8zWmw=,tag:ChCiwDII6X7C8tfW81YpcQ==,type:str]
sops:
  age:
    - recipient: age1dq2tahm820v40c0d55p0x84hlt9tlunh5lq32gr9lszkwelpv4mqv2wc0v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZ3NOVmpMcDQ1WmFpTHFH
        NndnMUxrSG5rNkVWMHY4UFJnbFNhclg1SlQwCldnZVZGZThXMXpPK05raFF5Y2tu
        UzJHNnRDOUJ2UTFjNGVBQy9EL1Y2akkKLS0tIDZFZHpDT2JydCt1dW5kNDRnUVZV
        WlVtTjk4MkVMSFRWeTFjY1pqTk8ySzQKEhWSs4dkqL0oIFIkijqa32tMJcbhq+L1
        ff3AaDxV2dYMxxbysOXwKVl94RcZkCsPka8/i35ZAOcMviugfvwW4w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T19:44:53Z"
  mac: ENC[AES256_GCM,data:YEHMot7BbY8xTd8b6fv5kSScqoEskLufESVGTAj2oTVIHQKG87fljpIBeM2uEEKckhbQFXBJ0GVUR4no8OvUShyVX70VZ7GVFa0v0edxJdHvDFTJTeEH07VOVACjlxh1vSqTGYSWbCyVpgKZlkC0WTWr6EAg6Gwj9LWjRNDNyAA=,iv:7fjwg1l/FazbGoMyn3ncRIkZ2+qjIMt4F4HC5x4bcTI=,tag:MXXFlT6CWPKnYFmaImGX6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
