apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Be9GzagiPVxtxAZfWgFVuQ==,iv:1Dh7eIyISFMIfw7ACsrktsKHeQBiHCWepw7GOgeA00A=,tag:n9KHpvaxaGlEJib1T7FEZg==,type:str]
sops:
  age:
    - recipient: age1dq2tahm820v40c0d55p0x84hlt9tlunh5lq32gr9lszkwelpv4mqv2wc0v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RXpIZ0dnWURqOFgzWllM
        TDNhNHRja3NHc3NDb25YdWRNM0hrVllsbkVnCkUwSmYvVTNpZU1KMENxQm5uOEYv
        Y0NLLzRldTZaRE9YMWdxWEVNOGlSbDAKLS0tIEJyUzF1Mi91YnpnSTZyVlo0eUZz
        S2NFZVNCaDZlalV4UTBZd2V3ajh2TEEKPcPuSyyRgOvKV5bYUdtp9EKTHQJqi3MP
        pGII0LH/r0So7O5JLiCLibkqglV3uhRRvShlgYJifUsNMwh3YVzwLg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T17:45:29Z"
  mac: ENC[AES256_GCM,data:mila6XGD3LNw7Ub859G1sh8N5xrreUj26vwf9fG/L1wyevdxbIcTOn3bZu7igJNjkCOuIJQFADZUysohiUeZSg96hGBXwq5f9Is6y/JQyjJy+3niX2P3ZbDLifbCfhnNz8Euh1RcIWXsxEpWJv1ObRCvgj9nTbZLaOsc/JK47v0=,iv:6V3In/mzkNEkIq1In8uHSdlON0SLYHu/RegHaiP2vjw=,tag:pW6hZJhjPlYo0VepPlaEqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
