apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:vNPG2st0VCnWXhADf8/Lrg==,iv:x+ymy/DM6nXEm06sR5fQ3qB/H9QzQ91o/lwYDXOjTT0=,tag:ZEfwkneq+DHstVQGQ2Ef7w==,type:str]
sops:
  age:
    - recipient: age1dq2tahm820v40c0d55p0x84hlt9tlunh5lq32gr9lszkwelpv4mqv2wc0v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTlI2R3dVcWpFTDJDdlVW
        cWJyVlloSVB1N2hVNzJkbXVYUmJGN2ZubTNZCkY1enBIc3pSR1BYYWdjYWZaV1J1
        YkljRHQ5Qm0va2lFN2t4RUJLVDFlSTgKLS0tIGpZL3prVWFQRzlraHZrSVo0N2ty
        TE9aR3ZXQ0c0QUtsZmRTQzlZQzlzTXcKK5SQrq0lKQDw4+3xrgO9LKg3jY/zuxNh
        acH1sThwrMltq7Yh5KKhnA/2/H7DI6dS3PVDTnVmP6LMdc2ISt5HXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T19:44:53Z"
  mac: ENC[AES256_GCM,data:UE9uGamh6vwQmfcHmZmkqqvJXyF2rlIrlTt6fZuUYcxy3BgdTduD/8aO3GKH2iEqHMVReMuSrsRoH/5CpyT1bKHTooO8veySDiWUQeXX4vwAFUHKSJK8ywT+pJ5+HUjwNT302R8SfWf18j27B3J3rM6/iSP4C8GHEkXGrUYL9wQ=,iv:glKozwz6i3D5fsKXGjlu5ttCjGuGIl6LmCUeF/GYzJQ=,tag:vWhi1iWpyu9MwH9ZDRJvDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
