apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:2nTilmEpFtuAVmLX0ejYyuUdgw55dyXvbuWzMduZI/raQWUg1GALhbJRV8Yfi/5ne8qYsrzMGGwwu1xXh+Vh+w==,iv:7y1sTtKFhbLODovORp6Y35lM9Reh/uLXSN0DP3jiv6s=,tag:810BnuoSYrCKr1RXfHTSeg==,type:str]
sops:
  age:
    - recipient: age1dq2tahm820v40c0d55p0x84hlt9tlunh5lq32gr9lszkwelpv4mqv2wc0v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSDdPQjd4ZTV1alpYREdO
        UjhQeGE0S0Q1QXNybjQybFJFUFZhNmdROEZvCnE5cXRZTFlCUjE0RHN0cVo5TGJz
        OTgyTzlPTzExcGdvTzh3cy9UL2VtbFkKLS0tIGFRT1BmYWUzT3laUTJrVmJZcXRh
        cThkY3kvUGVUOW9vL2pYV0Jic3JKNWMKWBDOPlKf7HuUSz4yzliqXls1TRU7Ln3D
        GkP6SXkDr8AojgKoPQlI9yVd9PlOcf0VrM05kPzYtlojTKRojkv/kQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T19:44:53Z"
  mac: ENC[AES256_GCM,data:42Xco4sCdT7A7GWjM2Koq6tTlNyB5nM9pxlTlj4gyJBmCQyxCerSetsRReH4AjNOqx/zWX0pIhMwhzrGoeGq19ifHavsTdY8ncej2ToJSoss/cHNTxEz6g4eFofSkmGhHyruFBh4m6K4kzrzt5HxRZovPQQvCJku+zHg6MfMwLw=,iv:fz0CB1ytEGINL72xLQd2DTyYdHpQuRns5pYbMOfNbgI=,tag:ruTGmCD4+vFPCFG1SSfv2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
