apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:8gvnb58F3qaUtqRJlI0uy9Xp9cZxHhjq3ZeEgEYUdTI3rsWkGsogO8coN1BDhq1LaYEI2FoGytZUzfjkdSO3xw==,iv:hybndjyL4EmWXDRRqmKCF4SUizdBX/qYeIjLzYY9NWE=,tag:4739XCXoKQnEpgkqpRcM0A==,type:str]
sops:
  age:
    - recipient: age1dq2tahm820v40c0d55p0x84hlt9tlunh5lq32gr9lszkwelpv4mqv2wc0v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TFNjREFUcmNzbW02ZzFx
        TFYreEUxNjRtTFQzVmUycEcwL2dIdzlpc1c0CnF6NFRKUHJ2QnBEM3VudXVjUFhH
        MXNMSUthczhLemkxVHhrRUtNVzE3dEkKLS0tIFJwMFQ1dEVmb2tOMEt1bktnVjMv
        OEovQzNWN1FBbmN2bXhKY3lhU3p3LzAKSvwGx4zu3BiQMxDY8JOyp8b6+8QlkA0y
        0Nzf4bpyT5PuFAJbKIvaFZrubEMOESke/5KLuraZPc6jBoGB6GHkWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T17:45:29Z"
  mac: ENC[AES256_GCM,data:mOKj6epc5E0JZNKlafskjgTkqzbR4MYdhWjR2v8chz9i7GtTzw9cohG7L9XWdq57TxyIeWrzT/nIVgULeErB7xFWI8mBxLqBxGfbsv1INGI2hESKbWnZ1Qwt1Z0ZczU5xzAcskm9Npgro/aNWYS4JBm103Bv2qY75uBz8qrZLzQ=,iv:yxAWJo1NqFOwPPyKHM9w1p9lT5XPR0YjFn2q1cA3rEc=,tag:SpTSDM8KXZ0Cds2dLlB/cA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
