apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:/PZxlDxuXqon5XeSYGZto4irLqy9k1iuH40MJjVWYkqPF4Co9b31L+dhKGNr+onGa/6MkmE81ZJlIUcsIwQKOZgXsmYgKMfHXQKD4xEXApMXj9Ktj5dOYb2OXt1WvFGB9J1iiMYmE0U8zofGQqa6qdj9rakSbjdxuazQkCKYx/ctzwRccng7GVQVbskC6JL4dKZDEnPzAzTLFYl1P74SsY8XbktbmY1pXkvr5dVpSokOLTgi,iv:dm5pVEFtd6malMZaybGU5cTOsvmcl6yiX2Va6l4SDuI=,tag:pi8xj+FzUplhoB9juwYcKQ==,type:str]
sops:
  age:
    - recipient: age1dq2tahm820v40c0d55p0x84hlt9tlunh5lq32gr9lszkwelpv4mqv2wc0v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYmNPb2IraERoc0tkcG9B
        UjNXbFJwT3hlQkRBcGdpczB1bS8zVHlEQW4wClN0Zno2WE5peDcvMEg2ay90c2lT
        OFJueCtQek10clF3TEdHc1laNlJYRnMKLS0tIFVsSGhnd3ltTU1iUFBRUm5obmF2
        eGFLemtVc1drTGRSdXppNW1MYk55Mk0KHRX3mPWIP8gihIIjClZN/LGs68MP1upg
        5j/aQ1yyrLzcM3lkZqiQmQ4/URqyMlO0SZJ/hQ6C/qOfLiQSU2q71g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T17:45:29Z"
  mac: ENC[AES256_GCM,data:UW2XY/Jo61tRUs6eN6vMHjUblnH1Dhv1MYPAnA3U/wy7Q1I++d231+yUO9N5C4QgJncXkRS0+IM3QyUkp5tBka4yhIT+9n5Y8kveGuy+2BUgPh57mntJKPdqkVngN0WJ5wZZ6YWw84SC+mFLouBmCAKesRTDviekzzIoY16GfH8=,iv:rxDx5WmkxURBrU8SDhbSpzfm4cQYU2Wpn322Sn1Ys+Y=,tag:3BY55U4EIFNtTSadzwEm9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
