apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:cETvZimCiHTnF90oqn153I30CrD4BUOqsTFSqZ7C7p18CfnfeacBz9m2fovK5m54CX+bzdmUP6DbMJwll27aVWm3z9BvjvlrMxnZAFHgR0mvbCFUkbmGbEKg/Q18tK8BSwLeP7Vr0yppq3q6NrNTpEVpaZ1znSkgqJryhdQ4th9TOuTiK72xgN5vMFl/MbpMV8gNmjgSdHsb3N61/8YGWpbUhto/oXpbxAGIjed4PKoxML25,iv:PkRTETJoKMuz6x01THKsUADRJ9aE57SpYpc4geJ7deI=,tag:fspz+a8rb+kK7swu0Ni0PA==,type:str]
sops:
  age:
    - recipient: age1dq2tahm820v40c0d55p0x84hlt9tlunh5lq32gr9lszkwelpv4mqv2wc0v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMkJaNUNuR2F0bFRRZ0g3
        SXk0NUVHQVdBSGZCUVNtaWcwK25aRDdxZkhBCldRZXp6VWh0N0F1a05yUmxVQUtB
        ZG1mRHhBMmZXOXN3MnZhc3FDUmcvMm8KLS0tIHhsd2IwQXN0TlNDblZKYU9jSmth
        SjZPTFVYV3RFTGdwU1RGZEtVYzlWMjAKg1O6DhL5LCwEnsUJ2yY4gplDUHI/DMN9
        zFmFmdsybagIuBBQToXHvWBy7iXpJxawCVzxChGI8kwtyuz2fpU3RQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T19:44:53Z"
  mac: ENC[AES256_GCM,data:JfnypFOHh+RCnv41JYRArJfgomRCg6F6usyyPeq41wQpMQE0OM+o+tqHZ5mazFqa5pUDEVCS4CEzvI0m8aBcXCTC72yqU50yuDuTXUPWU5P0zVsrGcustqdDF/PZMpcO9waieaqJFjBKrU7zZznzfffW6m506qD7S3T/CilkXiU=,iv:tG5foApwX1ufKDV6XlEAhXbRn07XV1eEru3SXh9VlDA=,tag:pxFX5EDoyPcpdeFg6qJWeQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
