apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Rpl0/Ce8jh3FtvMYKWW21ufErgOkc99t31g7oK57TYVdCTuF1z1/ow==,iv:JX1NIOFYJkrCJ1YVb1yG0pCblfz9Jt5asXAr4HWen6M=,tag:3Yw9BfisYE4VIwO6eee+iQ==,type:str]
sops:
  age:
    - recipient: age1dq2tahm820v40c0d55p0x84hlt9tlunh5lq32gr9lszkwelpv4mqv2wc0v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnamhaUnEyNldMS2dqc1k1
        UFdsMXBGeFdacWNLVnk5SUtHOXM5S2o1OGgwCnFKbFZSZWRSUlFSdlNvU2RzcDJ6
        bmozb0p2WUdvclNCVmdlQnEwVWJLdUUKLS0tIDF0S2JNeGZyVjVkQ3JXdE1adVFP
        YWUzNjMweUt1OVFlaXBnWk9xY0tDZ1EKSlMrBYoBtA0M7BzRZhuc5epgZIfXAjY5
        4EcjXqX9feiTwNhlrGmQJoyoHn6IYP5Ic7sMlMxIIUykPUA5CAf1Ew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T19:44:53Z"
  mac: ENC[AES256_GCM,data:FiiPp35sGqc3utjnyUlxppv6Udvr6GoyRtKliW4v6VYM/0zuz/HqAQEgsasexTspfHBaW5AXJAl1kP6s2sQ+HE7zYNsxkTgL/bPzAEg1kDTZs4NyXZCubZqY33NLaWNdT4qZ1A8+ZnTsLWvWwiMXfH2SDQr7j1Arh6yUg+BaJA8=,iv:AnznkOd3ORhEdeW0dr91XSjMWDX35JUacYyt90akXYM=,tag:2xIFZ6mQvO+pkg8c3RCK7Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
