apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:EopkNGeBQMZiTwEAYrglY4SlvtHPcpLOydh4JkzBkWFmyKkSnFpJkA==,iv:mW6MUuv0GHtuHvAcAFCEhu3+QLoNyL0D8YfHyRV5wl8=,tag:sJ+j9oGtDGpMChBp860+hQ==,type:str]
sops:
  age:
    - recipient: age1dq2tahm820v40c0d55p0x84hlt9tlunh5lq32gr9lszkwelpv4mqv2wc0v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdGNnUUd4Tm1JeWltSldC
        VS9nWGF2VnhiYk8xdHpIamhlbjlFUjRZS3p3CnAwcXAwWExDK2FIZGhvZkRpV3p2
        emZnbkI0SUR0dmVSSFp2TFJtVVp5TjAKLS0tIGwxOVpyRHlSdmp5cnFubjVzZHNX
        R3NBUVdqTTM0cklHeW13RG51eEhsN3MK0ilFNZMe7lHinP15Zm5rvDPBBjgFgOJd
        PxV/jYTYXgVZllFAWa6sMZ9OUayf66O4/uyldglrmSgw3E0qsEkpdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T17:45:29Z"
  mac: ENC[AES256_GCM,data:4/+yX8mElULCS3dsS0uRwVeWlNz1E+T78015ZCYgfALF67rWXYCaHFwXd4LusGsm2PhvS1C7Yp1oAF8GRZZry3B0ASX2zbKOZm4kB5nW2CaE6vm1a0RpxOkeo9oQNoNCcM7buaRvS7xS8OBxAFFOaBY8Xt2RGozqnaWrNYb2iko=,iv:US7N4eU7J8rVyIWEYmTsSfAkr7HWwnBxPQl+8gxwtsc=,tag:UrjtmaCqSqi9/6J3wo63IQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
