---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    ingress: false
    gateway: true
  settings.yaml: |
    title: Home Ops
    theme: dark
    color: slate
    headerStyle: clean
    layout:
      Apps:
        style: row
        columns: 3
      Infrastructure:
        style: row
        columns: 3
  services.yaml: |
    - Apps:
        - Jellyfin:
            icon: jellyfin.png
            href: https://jellyfin.${SECRET_DOMAIN}
            description: Media Server
            namespace: default
            app: jellyfin
    - Infrastructure:
        - Echo:
            icon: mdi-heart-pulse
            href: https://echo.${SECRET_DOMAIN}
            description: Echo Test Service
            namespace: default
            app: echo
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "beelink"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: duckduckgo
        target: _blank
  bookmarks.yaml: |
    - Cluster:
        - GitHub Repo:
            - abbr: GH
              href: https://github.com/Seegar99/home-ops
        - Flux Dashboard:
            - abbr: FX
              href: https://flux-webhook.${SECRET_DOMAIN}
  docker.yaml: ""
  custom.css: ""
  custom.js: ""
